### ISSUE TITLE
Criar workflow no GitHub Action

### ISSUE THREAD

**Issue by ImGabreuw** [ImGabreuw/dev-otaku#1]
# Criar workflow no GitHub Action

### **Função**

* Validar as dependências

* Testar

* Realizar o processo de _build_  da aplicação

### **Template workflow**

Java with Maven

```yaml
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

```
